spring.application.name=backend

#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=mypassword
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.secret=${JWT_SECRET:123456}